name: ESP32S3 WEMOS Controller
board: ESP32S3 WEMOS Controller

junction_deviation_mm: 0.02

stepping:
  engine: RMT
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 5
  disable_delay_us: 0
  segments: 12

spi:
  miso_pin: gpio.13
  mosi_pin: gpio.11
  sck_pin: gpio.12

sdcard:
  cs_pin: gpio.46
  card_detect_pin: NO_PIN
  frequency_hz: 400000
 
relay:
  direction_pin: NO_PIN
  output_pin: gpio.8
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0.000% 0=100.000% 1000=100.000%
  off_on_alarm: true

axes:
  x:
    steps_per_mm: 40
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 1000
    soft_limits: false

    motor0:
      standard_stepper:
        step_pin: gpio.4
        direction_pin: gpio.7
        disable_pin: NO_PIN

  y:
    steps_per_mm: 10
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 1000
    soft_limits: false

    motor0:
      standard_stepper:
        step_pin: gpio.1
        direction_pin: gpio.2
        disable_pin: NO_PIN

  z:
    steps_per_mm: 200
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 100
    soft_limits: false

    motor0:
      standard_stepper:
        step_pin: gpio.5
        direction_pin: gpio.6
        disable_pin: NO_PIN
